package com.joelmartinez.ordermanagementservice.controller.service;

import com.joelmartinez.ordermanagementservice.controller.service.request.CreateOrderRequest;
import com.joelmartinez.ordermanagementservice.controller.service.request.GiftCardRequest;
import com.joelmartinez.ordermanagementservice.controller.service.response.CreateOrderResponse;
import com.joelmartinez.ordermanagementservice.controller.service.response.GiftCardResponse;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.time.LocalDateTime;
import java.util.UUID;

@Service
public class OrderManagementServiceImpl implements OrderManagementService {

    private final WebClient.Builder webClient;

    public OrderManagementServiceImpl(WebClient.Builder webClient) {
        this.webClient = webClient;
    }

    @Override
    public CreateOrderResponse create(CreateOrderRequest request) {
        GiftCardRequest giftCardRequest = new GiftCardRequest();
        giftCardRequest.setValue(request.getGiftCardValue());

        // Call gift card supplier service to request a new gift card with the specified value
        GiftCardResponse giftCardResponse = webClient.build().post()
                .uri("http://giftcard-supplier-service/api/gift-card")
                .body(Mono.just(giftCardRequest), GiftCardRequest.class)
                .retrieve()
                .bodyToMono(GiftCardResponse.class)
                .block();

        if (giftCardResponse != null && giftCardResponse.getUuid() != null) {
            CreateOrderResponse response = new CreateOrderResponse();
            response.setOrderId(UUID.randomUUID().toString());
            response.setCreatedAt(LocalDateTime.now());
            response.setValue(request.getGiftCardValue());
            // Set the gift card code generated by the gift card supplier service
            response.setGiftCardCode(giftCardResponse.getUuid());

            return response;
        }

        throw new IllegalArgumentException("Purchase could not be processed.");
    }
}
